# Generated by Django 6.0.3 on 2026-06-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_assignment_course_alter_note_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.CharField(choices=[('All Courses', 'All Courses'), ('React Full Stack Development', 'React Full Stack Development'), ('Java Full Stack', 'Java Full Stack'), ('Python Development', 'Python Development'), ('MERN Stack', 'MERN Stack'), ('SQL & Data Analytics', 'SQL & Data Analytics'), ('Software Development', 'Software Development'), ('Testing', 'Testing'), ('UI/UX Design', 'UI/UX Design'), ('Devops', 'Devops'), ('DevOps', 'DevOps'), ('AI/ML', 'AI/ML'), ('AL/ML', 'AL/ML'), ('Data Science', 'Data Science'), ('Soft Skills', 'Soft Skills')], max_length=100)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
