# Generated by Django 6.0.3 on 2026-06-12 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='assigned_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.batch'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='assigned_mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.trainer'),
        ),
    ]
