# Generated by Django 6.0.6 on 2026-06-15 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_enrollment_assigned_batch_enrollment_assigned_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='assigned_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='App.batch'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='assigned_mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_enrollments', to='App.trainer'),
        ),
    ]
