# Generated by Django 4.2.29 on 2026-06-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_enrollment_assigned_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='course',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
